### PR TITLE
[READY] Moar logging

### PR DESCRIPTION
**Pull request by stevenjack**
container

### Problem

Currently there's no logging in the request based renderer.

### Solution

Adds the logging.

### CODE REVIEW

**Comment by stevenjack** [comment]
@darnould @Integralist guys happy for me to merge this?

**Comment by Integralist** [comment]
:cake: as per prev comment re: implementing AOP some point soon

**Comment by Integralist** [comment]
Did you dedupe?

**Comment by stevenjack** [comment]
@integralist yep, put it in the LogHelper class

**Comment by Integralist** [comment]
Moar :cake: for yer

**Pull request closed without merging**
